Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieTicketReservation.Models
{
    public class Cart
    {
        public int CartId { get; set; } //PK

        public int ProductId { get; set; }

        public DateTime DateCreated { get; set; }

        public string CustomerId { get; set; }

        public int Quantity { get; set; }

        public double Price { get; set; }

        public Movies movies { get; set; }
    }
}

Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieTicketReservation.Data;
using MovieTicketReservation.Models;

namespace MovieTicketReservation.Controllers
{
    [Authorize]
    public class MoviesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MoviesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Movies
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.movies.Include(m => m.category);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Movies/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movies = await _context.movies
                .Include(m => m.category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movies == null)
            {
                return NotFound();
            }

            return View(movies);
        }

        // GET: Movies/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.categories, "CategoryId", "Name");
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MovieName,DirectorName,ReleaseDate,Rating,Price,CategoryId")] Movies movies)
        {
            if (ModelState.IsValid)
            {
                _context.Add(movies);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.categories, "CategoryId", "Name", movies.CategoryId);
            return View(movies);
        }

        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movies = await _context.movies.FindAsync(id);
            if (movies == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.categories, "CategoryId", "Name", movies.CategoryId);
            return View(movies);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MovieName,DirectorName,ReleaseDate,Rating,Price,CategoryId")] Movies movies)
        {
            if (id != movies.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movies);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MoviesExists(movies.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.categories, "CategoryId", "Name", movies.CategoryId);
            return View(movies);
        }

        // GET: Movies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movies = await _context.movies
                .Include(m => m.category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movies == null)
            {
                return NotFound();
            }

            return View(movies);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movies = await _context.movies.FindAsync(id);
            _context.movies.Remove(movies);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MoviesExists(int id)
        {
            return _context.movies.Any(e => e.Id == id);
        }
    }
}

Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieTicketReservation.Data;
using MovieTicketReservation.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Configuration;
using Stripe;
using Stripe.Checkout;


namespace MovieTicketReservation.Controllers
{

    public class ShopController : Controller
    {
        private readonly ApplicationDbContext _context;
        private IConfiguration _iconfiguation;

        public ShopController(ApplicationDbContext context, IConfiguration iconfiguation)
        {
            _context = context;
            _iconfiguation = iconfiguation;
        }
        public IActionResult Index()
        {
            var categories = _context.categories.OrderBy(c => c.Name).ToList();
            return View(categories);
        }

        //Shop/Browse
        public IActionResult Browse(int id)
        {
            var products = _context.movies.Where(p => p.CategoryId == id).OrderBy(p => p.MovieName).ToList();
            ViewBag.category = _context.categories.Find(id).Name.ToString();
            return View(products);
        }

        private string GetCustomerId()
        {
            // check the session for an existing CustomerId
            if (HttpContext.Session.GetString("CustomerId") == null)
            {
                // if we don't already have an existing CustomerId in the session, check if customer is logged in
                var CustomerId = "";

                // if customer is logged in, use their email as the CustomerId
                if (User.Identity.IsAuthenticated)
                {
                    CustomerId = User.Identity.Name; //Name = email address
                }
                // if the customer is anonymous, use Guid to create a new identifier
                else
                {
                    CustomerId = Guid.NewGuid().ToString();
                }
                // now store the CustomerId in a session variable
                HttpContext.Session.SetString("CustomerId", CustomerId);
            }
            // return the Session variable
            return HttpContext.Session.GetString("CustomerId");
        }

        public async Task<IActionResult> AddToCart2(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movies = await _context.movies
                .Include(m => m.category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movies == null)
            {
                return NotFound();
            }

            var ProductId = movies.Id;

            int Quantity = 1;


            var price = _context.movies.Find(ProductId).Price;

            var currentDateTime = DateTime.Now;

            var CustomerId = GetCustomerId();

            var cart = new Cart
            {
                ProductId = ProductId,
                Quantity = Quantity,
                Price = price,
                DateCreated = currentDateTime,
                CustomerId = CustomerId
            };

            _context.Carts.Add(cart);
            _context.SaveChanges();

            int ItemCount = 0;
            if (HttpContext.Session.GetInt32("ItemCount") != null)
                ItemCount = (int)HttpContext.Session.GetInt32("ItemCount");

            HttpContext.Session.SetInt32("ItemCount", ++ItemCount);

            return RedirectToAction("Cart");
        }

        public IActionResult AddToCart(int ProductId, int Quantity)
        {
            var price = _context.movies.Find(ProductId).Price;

            var currentDateTime = DateTime.Now;

            var CustomerId = GetCustomerId();

            var cart = new Cart
            {
                ProductId = ProductId,
                Quantity = Quantity,
                Price = price,
                DateCreated = currentDateTime,
                CustomerId = CustomerId
            };

            _context.Carts.Add(cart);
            _context.SaveChanges();

            int ItemCount = 0;
            if (HttpContext.Session.GetInt32("ItemCount") != null)
                ItemCount = (int)HttpContext.Session.GetInt32("ItemCount");

            HttpContext.Session.SetInt32("ItemCount", ++ItemCount);

            return RedirectToAction("Cart");
        }


        //GET /Shop/Cart
        public IActionResult Cart()
        {
            // fetch current cart for display
            var CustomerId = "";
            // in case user comes to cart page before adding anything, identify them first
            if (HttpContext.Session.GetString("CustomerId") == null)
            {
                CustomerId = GetCustomerId();
            }
            else
            {
                CustomerId = HttpContext.Session.GetString("CustomerId");
            }

            // query the db for this customer
            //Add the "Include(c => c.Product)" to have our query include the Parent Products into our cart
            var cartItems = _context.Carts.Include(c => c.movies).Where(c => c.CustomerId == CustomerId).ToList();

            // pass the data to the view for display
            return View(cartItems);
        }



        //GET /Shop/RemoveFromCart
        public IActionResult RemoveFromCart(int id)
        {
            // find the item with this PK value
            var cartItem = _context.Carts.Find(id);

            // delete record from Carts table
            if (cartItem != null)
            {
                _context.Carts.Remove(cartItem);
                _context.SaveChanges();
            }


            int ItemCount = 0;
            if (HttpContext.Session.GetInt32("ItemCount") != null)
                ItemCount = (int)HttpContext.Session.GetInt32("ItemCount");

            HttpContext.Session.SetInt32("ItemCount", --ItemCount);

            //redirect to updated Cart
            return RedirectToAction("Cart");
        }

        //Shop/Checkout
        [Authorize]
        public IActionResult Checkout()
        {
            return View();
        }

        //POST: /Shop/Checkout
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Checkout([Bind("FirstName, LastName, Address, City, Province, PostalCode")] Models.Order order)
        {
            //Populate the 3 automatic Order properties
            order.OrderDate = DateTime.Now;
            order.CustomerId = User.Identity.Name;
            //calc order total based on the current cart
            order.Total = (from c in _context.Carts
                           where c.CustomerId == HttpContext.Session.GetString("CustomerId")
                           select c.Quantity * c.Price).Sum();

            //use SessionExtension Obj to store the order Obj in a session variable
            HttpContext.Session.SetObject("Order", order);

            //redirect to Payment Page
            return RedirectToAction("Payment");
        }

        //GET: /Cart/Payment
        [Authorize]
        public IActionResult Payment()
        {
            var order = HttpContext.Session.GetObject<Models.Order>("Order");

            ViewBag.Total = order.Total;

            // also use the ViewBag to set the PublishableKey, which we can read from the Configuration
            ViewBag.PublishableKey = _iconfiguation.GetSection("Stripe")["PublishableKey"];

            // load the Payment view
            return View();
        }

        //POST /Shop/ProcessPayment
        [Authorize]
        [HttpPost]
        public IActionResult ProcessPayment()
        {
            var order = HttpContext.Session.GetObject<Models.Order>("Order");
            // get the Stripe Secret Key from the configuration and pass it before we can create a new checkout session
            StripeConfiguration.ApiKey = _iconfiguation.GetSection("Stripe")["SecretKey"];

            // code will go here to create and submit Stripe payment charge
            var options = new SessionCreateOptions
            {
                PaymentMethodTypes = new List<string>
                {
                  "card",
                },
                LineItems = new List<SessionLineItemOptions>
                {
                  new SessionLineItemOptions
                  {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                      UnitAmount = (long?)(order.Total * 100),
                      Currency = "cad",
                      ProductData = new SessionLineItemPriceDataProductDataOptions
                      {
                        Name = "Movie Ticket Reservation",
                      },
                    },
                    Quantity = 1,
                  },
                },
                Mode = "payment",
                SuccessUrl = "https://" + Request.Host + "/Shop/SaveOrder",
                CancelUrl = "https://" + Request.Host + "/Shop/Cart"
            };
            var service = new SessionService();
            Stripe.Checkout.Session session = service.Create(options);
            return Json(new { id = session.Id });
        }
        // GET: /Shop/SaveOrder
        [Authorize]
        public IActionResult SaveOrder()
        {
            // get the order from the session variable
            var order = HttpContext.Session.GetObject<Models.Order>("Order");
            // save as new order to the db
            _context.Order.Add(order);
            _context.SaveChanges();

            // save the line items as new order details records
            var cartItems = _context.Carts.Where(c => c.CustomerId == HttpContext.Session.GetString("CustomerId"));
            foreach (var item in cartItems)
            {
                var orderDetail = new OrderDetail
                {
                    ProductId = item.ProductId,

Views/Shop/Browse.cshtml
@model IEnumerable<MovieTicketReservation.Models.Movies>

<h1>Browse our Categories</h1>

@if (ViewBag.Category != null)
{
    <h2>@ViewBag.category</h2>
}

<section>
    <div class="row">

        @foreach (var p in Model)
        {
            <div class="col-sm-6 col-lg-4 mb-3">
                <div class="card mb-3 text-center h-100">
                    <div class="card-body">
                        <h5>
                            <a asp-controller="Movies" asp-action="Details" asp-route-id="@p.Id">@p.MovieName</a>
                        </h5>
                        <h6>
                            @String.Format("${0:#,0}", p.Price)
                        </h6>
                        <p>
                            @p.DirectorName
                        </p>

                        <!--Form-->
                        <form method="post" action="/Shop/AddToCart">
                            <!--Hidden Field forhte selected produict id-->
                            <input type="hidden" id="ProductId" name="ProductId" value="@p.Id" />
                            <div class="form-group">
                                <label class="control-label" for="Quantity">Quantity: </label>
                                <input name="Quantity" id="Quantity" required min="1" max="99999" type="number" class="input-small" />
                            </div>
                            <button class="btn btn-primary">Add To Cart</button>
                        </form>
                    </div>
                </div>
            </div>
        }
    </div>
</section>

Views/Shop/Cart.cshtml
@model IEnumerable<MovieTicketReservation.Models.Cart>

@{
    ViewData["Title"] = " Your Cart";
    Layout = "~/Views/Shared/_Layout.cshtml";
    double total = 0;
}

<h1>Your Cart</h1>


<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.movies.MovieName)
            </th>
            <th class="text-right">
                @Html.DisplayNameFor(model => model.movies.DirectorName)
            </th>
            <th class="text-right">
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th class="text-right">
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            total += (item.Quantity * item.Price);
            <tr>
                <td>
                    <a asp-controller="Pastes" asp-action="Details" asp-route-id="@item.ProductId">@item.movies.MovieName</a>
                </td>
                <td class="text-right">
                    @item.movies.DirectorName
                </td>
                
                <td class="text-right">
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td class="text-right">
                    @String.Format("${0:#,0}", item.Price)
                </td>
                <td>
                    <a asp-action="RemoveFromCart" asp-route-id="@item.CartId">Delete</a>
                </td>
            </tr>
        }

        <tr>
            <td colspan="4" class="text-right">
                @String.Format("${0:#,0}", total)
            </td>
            <td>
                <a class="btn btn-primary" asp-action="Index"> Keep Shopping</a>
                <a class="btn btn-primary" asp-action="Checkout">Check Out</a>
            </td>
        </tr>

    </tbody>
</table>

Views/Shop/Checkout.cshtml
@model MovieTicketReservation.Models.Order

@{
    ViewData["Title"] = "Checkout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Checkout</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Checkout">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" required />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" required />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Province" class="control-label"></label>
                <input asp-for="Province" class="form-control" required />
                <span asp-validation-for="Province" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" required />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Payment >>" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Shop/Index.cshtml
@model IEnumerable<MovieTicketReservation.Models.Category>

@{
    ViewData["Title"] = "All Categories";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    
<h1>Choose Any Category</h1>

<section>
    <div class="row">

        @foreach (var item in Model)
        {
            <div class="col-sm-6 col-lg-4 mb-3">
                <div class="card mb-3 text-center h-100">
                    <div class="card-body">
                        <a asp-controller="Shop" asp-action="Browse" asp-route-id="@item.CategoryId">@item.Name</a>
                    </div>
                </div>
            </div>
        }
    </div>
</section>

Views/Shop/Payment.cshtml
<script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
<script src="https://js.stripe.com/v3/"></script>


<section>
    <div class="product">

        <div class="description">
            <h3>Your Order Total</h3>
            <h5>@String.Format("${0:#,0}", ViewBag.Total)</h5>
        </div>
    </div>
    <button id="checkout-button" class="btn btn-primary">Continue to Payment >></button>
</section>

<script type="text/javascript">
    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe("@ViewBag.PublishableKey");
    var checkoutButton = document.getElementById("checkout-button");
    checkoutButton.addEventListener("click", function () {
        fetch("/Shop/ProcessPayment", {
            method: "POST",
        })
            .then(function (response) {
                return response.json();
            })
            .then(function (session) {
                return stripe.redirectToCheckout({ sessionId: session.id });
            })
            .then(function (result) {
                // If redirectToCheckout fails due to a browser or network
                // error, you should display the localized error message to your
                // customer using error.message.
                if (result.error) {
                    alert(result.error.message);
                }
            })
            .catch(function (error) {
                console.error("Error:", error);
            });
    });
</script>